config/routes.rb
Resume::Application.routes.draw do
  get "latex_resume/index"
  get "latex_resume/source"
  get "latex_resume/generate"

  root :to => 'latex_resume#index'

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/latex_resume_controller.rb
class LatexResumeController < ApplicationController

	@@source_tex_file = "config/resume.tex"

  def index
  end

  def source
		root_dir = 'public/tmp/src'
		public_file = File.join( root_dir, 'resume_source' )
		FileUtils.mkdir_p( root_dir )
		FileUtils.cp( @@source_tex_file, public_file )

		# dont need the 'public' in the redirect path
		redirect_path = public_file.gsub( /public/, '' )

		redirect_to redirect_path 
  end

  def generate
		root_dir = 'public/tmp/pdf'
		command = "pdflatex -output-dir=public/tmp/pdf #{@@source_tex_file}"
		output_file = File.join( root_dir, File.basename( @@source_tex_file, ".*" ) + ".pdf" )

		raise "Error running: #{command}" unless system( command )
		raise "Missing output file: #{output_file}" unless File.file? output_file

		# dont need the 'public' in the redirect path
		redirect_path = output_file.gsub( /public/, '' )
		redirect_to redirect_path
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/latex_resume_helper.rb
module LatexResumeHelper
end

app/views/latex_resume/generate.html.erb
<h1>LatexResume#generate</h1>
<p>Find me in app/views/latex_resume/generate.html.erb</p>

app/views/latex_resume/index.html.erb
<h1>LatexResume#index</h1>

<%= link_to 'config/resume.tex', latex_resume_source_path %>
<%= link_to 'Latex Generated PDF', latex_resume_generate_path %>

app/views/latex_resume/source.html.erb
<h1>LatexResume#source</h1>
<p>Find me in app/views/latex_resume/source.html.erb</p>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Resume</title>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>